### ISSUE TITLE
Not working for ARM64 arch

### ISSUE THREAD

**Issue by Siltaz** [bitwarden/sm-action#115]
```
/home/ubuntu/actions-runner/_work/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/binding.js:216
    throw loadError;
    ^

Error: Cannot find module '@bitwarden/sdk-napi-linux-arm64-gnu'
Require stack:
- /home/ubuntu/actions-runner/_work/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/binding.js
- /home/ubuntu/actions-runner/_work/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/dist/bitwarden_client/index.js
- /home/ubuntu/actions-runner/_work/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/dist/index.js
- /home/ubuntu/actions-runner/_work/_actions/bitwarden/sm-action/v2/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:[9](https://github.com/FiberApps/reusable-workflows/actions/runs/9212059325/job/25342857998#step:3:10)01:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/ubuntu/actions-runner/_work/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/binding.js:187:31)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:[10](https://github.com/FiberApps/reusable-workflows/actions/runs/9212059325/job/25342857998#step:3:11))
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:[11](https://github.com/FiberApps/reusable-workflows/actions/runs/9212059325/job/25342857998#step:3:12)15:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ubuntu/actions-runner/_work/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/binding.js',
    '/home/ubuntu/actions-runner/_work/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/dist/bitwarden_client/index.js',
    '/home/ubuntu/actions-runner/_work/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/dist/index.js',
    '/home/ubuntu/actions-runner/_work/_actions/bitwarden/sm-action/v2/dist/index.js'
  ]
}

Node.js v20.8.1
```

**Comment by dben** [comment]
I'm getting the same error for x64 when running on a native gha ubuntu 22 runner:

```
/__w/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/binding.js:216
    throw loadError;
    ^

Error: Cannot find module '@bitwarden/sdk-napi-linux-x64-musl'
Require stack:
- /__w/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/binding.js
- /__w/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/dist/bitwarden_client/index.js
- /__w/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/dist/index.js
- /__w/_actions/bitwarden/sm-action/v2/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/__w/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/binding.js:151:31)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:14[16](https://github.com/enosix/dn-ScratchOrgMgr/actions/runs/9777780938/job/27009938080#step:4:17):10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:[19](https://github.com/enosix/dn-ScratchOrgMgr/actions/runs/9777780938/job/27009938080#step:4:20)) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/__w/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/binding.js',
    '/__w/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/dist/bitwarden_client/index.js',
    '/__w/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/dist/index.js',
    '/__w/_actions/bitwarden/sm-action/v2/dist/index.js'
  ]
}

Node.js v20.13.1
```

**Comment by pshirshov** [comment]
Same here.

```
Run bitwarden/sm-action@v2
/run/github-runner/izumi/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/binding.js:216
    throw loadError;
    ^

Error: Cannot find module '@bitwarden/sdk-napi-linux-arm64-gnu'
Require stack:
- /run/github-runner/izumi/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/binding.js
- /run/github-runner/izumi/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/dist/bitwarden_client/index.js
- /run/github-runner/izumi/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/dist/index.js
- /run/github-runner/izumi/_actions/bitwarden/sm-action/v2/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/run/github-runner/izumi/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/binding.js:187:31)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/run/github-runner/izumi/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/binding.js',
    '/run/github-runner/izumi/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/dist/bitwarden_client/index.js',
    '/run/github-runner/izumi/_actions/bitwarden/sm-action/v2/dist/node_modules/@bitwarden/sdk-napi/dist/index.js',
    '/run/github-runner/izumi/_actions/bitwarden/sm-action/v2/dist/index.js'
  ]
}
```

**Comment by pshirshov** [comment]
Upstream issue: https://github.com/bitwarden/sdk-sm/issues/1154
